# FinOps Infrastructure Audit Report
**Author:** Gloria Jean Cosentino
**Project:** Cloud Cost Governance & Optimization
**Date:** May 2026

---

### Executive Summary
This notebook automates the identification of underutilized "zombie" infrastructure assets. By applying a standardized FinOps methodology, this audit transforms raw cloud cost data into actionable fiscal intelligence.

* **Pilot Recoverable Capital:** $32,640.00 (Annualized)
* **Projected Enterprise Impact:** $32,640,000.00
* **Strategic Goal:** Shift from reactive troubleshooting to automated, policy-driven infrastructure lifecycle management.

---

In [2]:
import pandas as pd
import pandasql as ps

# Create the data
data = {
    'instance_id': ['dev-test-b', 'prod-web-01', 'sandbox-99', 'db-backup-04', 'uat-app-02'],
    'department_owner': ['Engineering', 'Marketing', 'Finance', 'Engineering', 'Underwriting'],
    'monthly_cost': [850, 2500, 400, 1200, 950],
    'average_cpu_utilization': [1.2, 78.5, 2.5, 0.5, 2.8],
    'consecutive_days_idle': [14, 0, 8, 20, 12]
}
df = pd.DataFrame(data)

print("Setup Complete: 'df' and 'ps' are now loaded in memory.")

Setup Complete: 'df' and 'ps' are now loaded in memory.

In [3]:
# --- 5. THE AUDIT & IMPACT REPORT ---

# Run the query
audit_results = ps.sqldf("""
SELECT 
    instance_id,
    department_owner,
    monthly_cost,
    average_cpu_utilization,
    consecutive_days_idle,
    (monthly_cost * 0.8) as potential_savings 
FROM 
    df
WHERE 
    average_cpu_utilization < 3.0
    AND consecutive_days_idle >= 7
ORDER BY 
    monthly_cost DESC;
""", locals())

# Calculate and print the summary
total_potential = audit_results['potential_savings'].sum()

print("--- AUDIT REPORT ---")
display(audit_results)
print(f"\nTotal Recoverable Capital: ${total_potential:,.2f}")

--- AUDIT REPORT ---

,instance_id,department_owner,monthly_cost,average_cpu_utilization,consecutive_days_idle,potential_savings
0,db-backup-04,Engineering,1200,0.5,20,960.0
1,uat-app-02,Underwriting,950,2.8,12,760.0
2,dev-test-b,Engineering,850,1.2,14,680.0
3,sandbox-99,Finance,400,2.5,8,320.0

Total Recoverable Capital: $2,720.00

### 1. Project Initialization & Data Ingestion
**Objective:** Establish the foundational infrastructure dataset for the Zurich Cloud Audit. 

**Logic:**
- We define a Python dictionary representing our cloud assets (Instance ID, Owner, Cost, CPU, and Idle Days).
- We convert this into a Pandas DataFrame (`df`) to enable SQL-based querying. This simulates an enterprise environment where data is pulled from a cloud management platform (e.g., AWS Cost Explorer or Azure Advisor).

In [ ]:
import pandas as pd
import pandasql as ps

# Create the data
data = {
    'instance_id': ['dev-test-b', 'prod-web-01', 'sandbox-99', 'db-backup-04', 'uat-app-02'],
    'department_owner': ['Engineering', 'Marketing', 'Finance', 'Engineering', 'Underwriting'],
    'monthly_cost': [850, 2500, 400, 1200, 950],
    'average_cpu_utilization': [1.2, 78.5, 2.5, 0.5, 2.8],
    'consecutive_days_idle': [14, 0, 8, 20, 12]
}
df = pd.DataFrame(data)

print("Setup Complete: Dataframe 'df' is loaded.")

### 2. Infrastructure Efficiency Audit
**Objective:** Filter the infrastructure to isolate "zombie" assets that are costing the firm money without providing utility.

**Criteria:**
- **Underutilization:** CPU usage < 3%.
- **Stagnation:** Idle for 7+ consecutive days.
- **Financial Calculation:** We calculate `potential_savings` as 80% of the `monthly_cost`, providing a conservative estimate of reclaimable budget.

In [5]:
# Run the audit and calculate potential savings
audit_results = ps.sqldf("""
SELECT 
    instance_id,
    department_owner,
    monthly_cost,
    average_cpu_utilization,
    consecutive_days_idle,
    (monthly_cost * 0.8) as potential_savings 
FROM 
    df
WHERE 
    average_cpu_utilization < 3.0
    AND consecutive_days_idle >= 7
ORDER BY 
    monthly_cost DESC;
""", locals())

# Display the findings
display(audit_results)
print(f"Total Recoverable Capital: ${audit_results['potential_savings'].sum():,.2f}")

,instance_id,department_owner,monthly_cost,average_cpu_utilization,consecutive_days_idle,potential_savings
0,db-backup-04,Engineering,1200,0.5,20,960.0
1,uat-app-02,Underwriting,950,2.8,12,760.0
2,dev-test-b,Engineering,850,1.2,14,680.0
3,sandbox-99,Finance,400,2.5,8,320.0

Total Recoverable Capital: $2,720.00

### 3. Departmental Accountability Analysis
**Objective:** Aggregate the waste by department to identify where governance gaps exist.

**Strategic Value:**
- By grouping by `department_owner`, we move from technical reporting to organizational insights. 
- This highlights which departments require updated lifecycle policies, allowing for targeted remediation rather than generic cost-cutting.

In [6]:
# Grouping waste by department
dept_waste = audit_results.groupby('department_owner')['potential_savings'].sum().sort_values(ascending=False).reset_index()

print("--- WASTE BY DEPARTMENT ---")
display(dept_waste)

--- WASTE BY DEPARTMENT ---

  department_owner  potential_savings
0      Engineering             1640.0
1     Underwriting              760.0
2          Finance              320.0

### 4. Summary & Recommendations
**Executive Conclusion:** The audit identifies $2,720.00 in monthly potential savings ($32,640.00 annualized). 

**Strategic Recommendations:**
1. **Engineering Governance:** Given that Engineering holds the largest share of underutilized assets, I recommend implementing an automated "Resource Scheduler" to auto-stop development instances outside of business hours.
2. **Finance & Underwriting Review:** Conduct a manual review of 'sandbox-99' and 'uat-app-02' to determine if these are legacy assets that have bypassed the decommissioning lifecycle.
3. **Continuous Monitoring:** Shift this audit from a point-in-time check to an automated, weekly KPI reporting process.

### 5. Enterprise-Scale Financial Impact
**Objective:** Project the fiscal impact across an enterprise environment to demonstrate the value of automated FinOps governance.

**Strategic Narrative:**
- The current pilot identifies $32,640 in annual waste from a sample set of five assets.
- When extrapolated across an enterprise portfolio of 5,000+ similar instances, the projected annual cost avoidance is estimated to exceed **$32.6M**.
- This highlights the necessity of shifting from manual cost-cutting to an automated "FinOps-as-a-Service" model to maintain operational margin.

In [8]:
# 1. Ensure the annual calculation is performed on the departmental data
dept_waste['annual_savings'] = dept_waste['potential_savings'] * 12

# 2. Calculate the Enterprise Impact
pilot_assets = len(df)
enterprise_assets = 5000  # Assumed portfolio size
scaling_factor = enterprise_assets / pilot_assets

total_annual_pilot_savings = dept_waste['annual_savings'].sum()
projected_enterprise_impact = total_annual_pilot_savings * scaling_factor

# 3. Display the final findings
print(f"--- ENTERPRISE IMPACT PROJECTION ---")
print(f"Pilot Monthly Savings: ${dept_waste['potential_savings'].sum():,.2f}")
print(f"Pilot Annual Savings: ${total_annual_pilot_savings:,.2f}")
print(f"Projected Annual Impact (at {enterprise_assets:,} assets): ${projected_enterprise_impact:,.2f}")

--- ENTERPRISE IMPACT PROJECTION ---
Pilot Monthly Savings: $2,720.00
Pilot Annual Savings: $32,640.00
Projected Annual Impact (at 5,000 assets): $32,640,000.00

### 📊 FinOps Executive Audit: Infrastructure Efficiency
**Portfolio Case Study: Zurich Global Infrastructure**

**Core Objective:** Quantify potential fiscal recovery through the identification of idle cloud assets using Python and SQL-based auditing.

**Key Performance Indicators (KPIs):**
- **Monthly Recoverable Capital:** $2,720.00
- **Annualized Impact (Pilot):** $32,640.00
- **Enterprise Potential (Scale):** $32,640,000.00

**Strategic Insight:**
The audit proves that decentralized resource lifecycle management is directly leaking budget. Implementation of automated decommissioning policies is the recommended path to protecting the operational margin.

### 5. Remediation Strategy: Automated Governance
**Objective:** Transition from manual audit to automated lifecycle management to prevent asset stagnation.

**Proposed Technical Controls:**
1. **Infrastructure as Code (IaC) Policies:** Enforce `TTL` (Time-To-Live) tags on all non-production assets.
2. **Automated Lifecycle Hooks:** Implement a serverless function (e.g., AWS Lambda or Azure Functions) that triggers a shutdown warning after 5 days of inactivity and executes a stop/terminate command after 7 days.
3. **Continuous Monitoring:** Shift from monthly reports to real-time dashboards that trigger alerts to department owners at the 3-day inactivity threshold.

In [9]:
import os
print(os.getcwd())

/home/6db77f0c-d501-45b8-bb4d-d347be482ea5